### ISSUE TITLE
GPU memory and training cost on ScanNet_v2

### ISSUE THREAD

**Issue by Yuxuan-W** [microsoft/Swin3D#8]
Thanks for your inspiring work! I noticed that in main paper the pre-training stage on Structured3D cost 488 and 703 GPU hours for Swin3D-S and Swin3D-L. May I also know the approximately GPU hours and memory cost when training from scratch on ScanNet_v2 that leads to 75.2(Swin3D-S*)/74.2(Swin3D-L*) val mIoU?

**Comment by Yukichiii** [comment]
For Swin3D-S, it takes 44 hours to train 600 epochs with four V100 GPUs on ScanNetv2. When batchsize is set to 2 for each GPU, it needs no more than 12G GPU memory.

As for Swin3D-L, it will take about 90 hours with four V100 GPUs. The batchsize is set to 3 and it will take around 28G GPU memory.
Since we finetune the whole model, training from scratch and finetune take about the same cost.

**Comment by Yuxuan-W** [comment]
Thank you so much!

**Comment by hpc100** [comment]
Which hyperparameter do you used for swin3D from scratch (eval_freq, ...), it's possible to have the log for Swin3D S & L without pretrained. Thank's

**Comment by hfutdzx** [comment]
I have a question。Did you mean one gpu needs no more than 12G GPU memory or four gpus need no more than 12G GPU memory in total？

**Comment by hfutdzx** [comment]
> For Swin3D-S, it takes 44 hours to train 600 epochs with four V100 GPUs on ScanNetv2. When batchsize is set to 2 for each GPU, it needs no more than 12G GPU memory.
> 
> As for Swin3D-L, it will take about 90 hours with four V100 GPUs. The batchsize is set to 3 and it will take around 28G GPU memory.
> Since we finetune the whole model, training from scratch and finetune take about the same cost.

i have a question。Did you mean one gpu needs no more than 12G GPU memory or four gpus need no more than 12G GPU memory in total？

**Comment by Yukichiii** [comment]
Each GPU needs no more than 12G GPU memory whose batchsize is 2.
